### ISSUE TITLE
Auto update server

### ISSUE THREAD

**Issue by mario123456789o** [ThomasKoscheck/WG-Verwaltung#14]
Have a python script checking for source code updates on github. If one is available, pull new code and restart server. In case of server crash, restart current version, if it crashes again, start old version and notify developer.

**Comment by mario123456789o** [comment]
Another idea. Maybe add a testserver on another port which gets automatically updated via git

**Comment by ThomasKoscheck** [comment]
fixed with branch features/devSupervisor
