### ISSUE TITLE
Development is only taking place in one master branch

### ISSUE THREAD

**Issue by DrNochi** [ThomasKoscheck/WG-Verwaltung#15]
You should use an additional branch for development, the master branch should be used for "finished"/releasable versions. Additionally, there should be separate branches for each feature that is being developed, that branch can be merged back into the main development branch when it's finished.

Take a look at this: http://nvie.com/posts/a-successful-git-branching-model/

**Comment by ThomasKoscheck** [comment]
Thanks for the advise.
Since we haven't had any production code yet, there was no need to introduce other branches.
However, we will implement this in the future.
